# Generated by Django 3.0.8 on 2020-08-04 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorite',
            field=models.ManyToManyField(blank=True, to='movies.Movie', verbose_name='favorite'),
        ),
    ]
