# Generated by Django 3.0.8 on 2020-08-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_profile_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='favorite',
        ),
        migrations.AlterField(
            model_name='movie',
            name='favourite',
            field=models.ManyToManyField(blank=True, to='movies.Profile', verbose_name='favourite'),
        ),
    ]
