# Generated by Django 3.0.8 on 2020-08-04 14:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0004_auto_20200804_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorite',
            field=models.ManyToManyField(blank=True, to='movies.Movie', verbose_name='favorite'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='favourite',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='favourite'),
        ),
    ]
