# Generated by Django 3.0.8 on 2020-08-04 14:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0008_movie_favourite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='favourite',
        ),
        migrations.AddField(
            model_name='movie',
            name='favourite',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='favourite'),
        ),
    ]
