# Generated by Django 3.0.8 on 2020-08-04 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_auto_20200804_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='favourite',
        ),
    ]
