# Generated by Django 3.0.8 on 2020-08-04 14:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0012_remove_movie_favor'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='favor',
            field=models.ManyToManyField(blank=True, related_name='favor', to=settings.AUTH_USER_MODEL),
        ),
    ]
