# Generated by Django 3.0.8 on 2020-08-04 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_movie_favor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='favorite',
        ),
        migrations.DeleteModel(
            name='FavoriteAnime',
        ),
    ]
