# Generated by Django 3.0.8 on 2020-10-02 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0024_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='search',
            field=models.CharField(blank=True, max_length=250, verbose_name='Поиск'),
        ),
    ]
